language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.10
  - ruby-head
  - jruby-9
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: jruby-head
  fast_finish: true
script: "bundle exec rake"
